events {}

http {
    include /etc/nginx/mime.types;
    resolver 127.0.0.11 valid=30s;

    upstream node_backend {
        least_conn;
        server backend:3000;
    }

    server {
        listen 80;
        server_name nfchealthcare.ddns.net;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name nfchealthcare.ddns.net;

        ssl_certificate /etc/letsencrypt/live/nfchealthcare.ddns.net/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/nfchealthcare.ddns.net/privkey.pem;

        location ~ ^/(api|auth|admin|hospital|admin-hospital|medical-record|receptionist|chatbot)(/|$) {
            proxy_pass http://node_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            client_max_body_size 30m;
        }

        location /ai/ {
            set $ai_srv "http://ai_model:8000";
            proxy_pass $ai_srv/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 120s;
            proxy_connect_timeout 10s;
            proxy_send_timeout 120s;
        }

        location /chat/ {
            set $chat_srv "http://chatbot:8001";
            proxy_pass $chat_srv/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            client_max_body_size 20m;
            proxy_read_timeout 120s;
            proxy_connect_timeout 10s;
            proxy_send_timeout 120s;
        }

        location / {
            # هنا التعديل المهم اللي كان مطلع إيرور
            proxy_pass http://frontend:80; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
